// 滑铁卢大学研究生重要日期（按学年分组，仅含 2026 秋季及以后入学学年）。
// 来源: uwaterloo.ca/important-dates/graduate
window.UW_EVENTS = [
  {
    "title_en": "Labour Day",
    "title_zh": "劳动节 (Labour Day)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-07",
    "end": "",
    "action": "全校停课、办公室关闭，享受假期吧～",
    "desc_en": "No classes and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Grad Orientation Week (in-person)",
    "title_zh": "研究生迎新指导周",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-07",
    "end": "2026-09-10",
    "action": "滑铁卢大学 9 月入学新生研究生「线下新生入学指导」周（9/7–9/10），由新生过渡组织(New Student Transition)统一举办。含研究生迎新会、欢迎与服务博览会、宿舍晚间社交等。面向所有 9 月入学的新生研究生，需提前在线注册；具体项目迎新请联系各自项目协调员。注册/咨询：gradready@uwaterloo.ca。",
    "desc_en": "In-person graduate orientation week for September-entry graduate students, organized by New Student Transition. Register in advance.",
    "academicYear": 2026
  },
  {
    "title_en": "Graduate Orientation",
    "title_zh": "研究生迎新会",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "今天（周二）是 2026 研究生迎新会！与研究生同学交流、探索校园、了解学校的服务与支持，是开学前必参加的活动。⚠️ 务必提前在线注册：即使无法参加迎新与服务博览会，也请注册以便现场签到并发放手环（签到 14:00–14:45）。当天所有活动（含晚间宿舍社交）均需佩戴手环。具体日程发至邮箱，亦可查 uwaterloo.ca/welcome-warriors/events/graduate-orientation。联系 gradready@uwaterloo.ca。",
    "desc_en": "Graduate Orientation on Sept 8 (Tue). Mandatory registration; wristband required for all day's events including the evening social.",
    "academicYear": 2026
  },
  {
    "title_en": "Welcome & Services Fair",
    "title_zh": "欢迎与服务博览会",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-07",
    "end": "",
    "action": "迎新前一日（周一）14:00–15:00 的「欢迎与服务博览会」，提前到校熟悉环境与各类支持服务。属迎新注册中标注「需注册」的活动之一，即使不参加也建议注册以便现场签到。",
    "desc_en": "Welcome & Services Fair, Mon Sept 7 2:00–3:00 PM. Part of the grad orientation registration.",
    "academicYear": 2026
  },
  {
    "title_en": "Indigenous Student Session",
    "title_zh": "原住民学生迎新会",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-07",
    "end": "",
    "action": "周一 13:30–16:30 由原住民关系办公室(Office of Indigenous Relations)为即将入学的原住民研究生/本科生举办的额外迎新会（在研究生迎新会前一天）。如符合资格，请在注册表中同时报名此次迎新会。",
    "desc_en": "Indigenous Student Session, Mon Sept 7 1:30–4:30 PM, by the Office of Indigenous Relations. Register via the same form.",
    "academicYear": 2026
  },
  {
    "title_en": "Welcome to the University",
    "title_zh": "欢迎来到大学",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "周二 15:00–15:30 的「欢迎来到大学」主旨环节，了解学校概览、资源与支持体系，迎新当天不可错过。",
    "desc_en": "Welcome to the University, Tue Sept 8 3:00–3:30 PM.",
    "academicYear": 2026
  },
  {
    "title_en": "Grad Residence Evening Social",
    "title_zh": "研究生宿舍晚间社交",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "周二 17:30–21:00 研究生宿舍晚间社交活动，结识同学、融入社群的好机会。⚠️ 需佩戴迎新手环方可参加，记得先完成 14:00–14:45 的现场签到注册再领手环。",
    "desc_en": "Grad Residence Evening Social, Tue Sept 8 5:30–9:00 PM. Wristband required.",
    "academicYear": 2026
  },
  {
    "title_en": "Grad Funding Session",
    "title_zh": "研究生经费来源讲座",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "周二 15:45–16:20 研究生经费来源讲座，了解奖学金、助教(TA)/助研(RA)等资助渠道与申请方式，对自费/带奖新生都值得一听。",
    "desc_en": "Grad Funding session, Tue Sept 8 3:45–4:20 PM.",
    "academicYear": 2026
  },
  {
    "title_en": "Human Library & Speed Networking",
    "title_zh": "真人图书馆 & 快速人脉拓展",
    "category": "迎新",
    "emoji": "🤝",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "周二下午的互动环节：真人图书馆 #1（15:45–16:20）、#2（16:35–17:10）与快速人脉拓展（16:35–17:10）。通过真实故事与学长学姐交流、快速拓展人脉，建议提前在注册表选好场次。",
    "desc_en": "Human Library #1/#2 and Speed Networking, Tue Sept 8 afternoon. Select sessions in the registration form.",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term begins",
    "title_zh": "Co-op 实习学期开始",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-08",
    "end": "",
    "action": "Co-op 实习学期开始，实习的同学按雇主安排入职报到（具体日期以雇主/个人情况为准）。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "Classes begin",
    "title_zh": "开课 · 学期第一天",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-09",
    "end": "",
    "action": "新学期开课啦！确认课表、上课地点和第一周作业，调好状态开学冲。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable start dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Not Fees Arranged (NFA) holds applied",
    "title_zh": "未安排缴费(NFA)冻结生效",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-23",
    "end": "",
    "action": "今天起未完成缴费安排的账户会被加上 NFA 冻结，影响后续选课等操作，尽快把费用处理好。",
    "desc_en": "Not Fees Arranged (NFA) holds are applied to student accounts which are not yet Fees Arranged for the term. Undergraduate students: Find out more about how this hold will impact your course registration process for future terms.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 100%",
    "title_zh": "100% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-09-29",
    "end": "",
    "action": "今天是全额(100%)退费的最后一天：若打算退课/退学期，今天前操作可拿回全部费用。",
    "desc_en": "Deadline to receive 100% of charges removed for withdrawing from the term, completing degree requirements, or dropping a course. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Class drop with grade of Withdrawn, no credit granted (WD)",
    "title_zh": "退课记 WD 期（不计学分）",
    "category": "退课",
    "emoji": "⚠️",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-01",
    "end": "2026-11-24",
    "action": "进入\"退课记 WD\"阶段：此后退课会在成绩单标记 Withdrawn(不计学分)。如要退课请权衡后尽早决定。",
    "desc_en": "During this period, graduate students can continue to drop classes in Quest but a grade of Withdrawn, no credit granted (WD) will be applied and the class will remain on the transcript. Note that WD is not an academic penalty. Outside of this period, students with special circumstances can petition to drop or add a class using a course drop add form (Graduate Studies forms website).",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to select an examination centre or submit a proctor for online course final examinations",
    "title_zh": "线上课程期末：选考点/提交监考人截止",
    "category": "考试",
    "emoji": "📚",
    "priority": 3,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-02",
    "end": "",
    "action": "重要截止：如你有线上课程期末考，今天前必须在系统选好考试中心或提交监考人(proctor)，错过会影响考试！",
    "desc_en": "View details about final examination arrangements for online courses on The Centre website. Deadline is 3 p.m. ET on date listed.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination schedule released",
    "title_zh": "期末考试安排发布",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-02",
    "end": "",
    "action": "期末考试时间表出来啦！登录 Quest 查好每门考试的时间、地点，早做规划。",
    "desc_en": "Visit the Final Examination Schedule website (authentication required) on or after this date to view the term's final examination schedule.",
    "academicYear": 2026
  },
  {
    "title_en": "Reading Week",
    "title_zh": "阅读周 / Reading Week（无课）",
    "category": "假期",
    "emoji": "🎉",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-10",
    "end": "2026-10-18",
    "action": "本周无课！正是赶论文、补作业、复习或好好喘口气的黄金时间，给自己排个计划。",
    "desc_en": "All classes cancelled; offices closed on the weekends and the holiday Monday. Undergraduate students: View the Undergraduate Studies Academic Calendar for more details. Graduate students: View the Graduate Studies Academic Calendar for more details.",
    "academicYear": 2026
  },
  {
    "title_en": "Thanksgiving Day",
    "title_zh": "感恩节 (Thanksgiving)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-12",
    "end": "",
    "action": "感恩节假期，全校放假，记得休息、也别忘了跟家人朋友道声谢～",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 50%",
    "title_zh": "50% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-23",
    "end": "",
    "action": "今天是 50% 退费的最后一天：若要退课/退学期，今天前操作还能退回一半费用，之后不退。",
    "desc_en": "Deadline to receive 50% of charges for tuition, co-op fee, and student services fees removed for withdrawing from the term, completing degree requirements, or dropping a course. All other charges remain on student accounts. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Convocation - fall 2026",
    "title_zh": "2026 秋季毕业典礼 (Convocation)",
    "category": "毕业",
    "emoji": "🎓",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-23",
    "end": "2026-10-24",
    "action": "秋季毕业典礼！毕业生留意典礼时间地点、着装与来宾安排，约上亲友一起见证～",
    "desc_en": "Visit the Convocation website for details.",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to arrange tuition and fees",
    "title_zh": "最后办理\"Fees Arranged\"截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 3,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-10-31",
    "end": "",
    "action": "最后期限：今天前必须完成学费缴清或办理\"Fees Arranged\"，否则可能被冻结/退课，务必今天搞定。",
    "desc_en": "Refer to tuition and fees deadlines . Late fees apply, see Student Financial Services for details. Visit the Finance website for instructions on submitting a Promissory Note .",
    "academicYear": 2026
  },
  {
    "title_en": "Class enrolment period",
    "title_zh": "选课期 (Class Enrolment)",
    "category": "选课",
    "emoji": "📝",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2026-12-07",
    "end": "2027-01-31",
    "action": "选课期开放！登录 Quest 尽早选好课/调整课表；注意：未办理缴费(Fees Arranged)的同学第3周结束会被系统退课。",
    "desc_en": "During this period, graduate students can enrol themselves in classes using Quest , and can also drop classes in Quest. Graduate students who are not fee arranged and have enrolled in classes will have their classes dropped at the end of the third week of classes (end of class enrolment period).",
    "academicYear": 2026
  },
  {
    "title_en": "Classes end",
    "title_zh": "停课 · 本学期课程结束",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-08",
    "end": "",
    "action": "今天是本学期最后一天上课，收尾好各科笔记和作业，准备进入复习/考试阶段。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable end dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Pre-examination study days",
    "title_zh": "考前复习日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-09",
    "end": "",
    "action": "考前复习日，无课。安心复习，制定好各科的备考计划。",
    "desc_en": "There are one or two study days each term, between the end of the Formal Lecture Period and the beginning of the Final Examination Period. No classes are to be held during study days, except where classes are rescheduled as the result of a campus-wide emergency closure.",
    "academicYear": 2026
  },
  {
    "title_en": "Final Examination Period",
    "title_zh": "期末考试期",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-10",
    "end": "2026-12-23",
    "action": "进入期末考试期，随时核对你的考试安排，合理规划复习节奏。",
    "desc_en": "The Final Examination Period begins on the first date listed, and ends with an emergency day. Students are expected to be available to write their final examination(s) for the entirety of the Final Examination Period, including the scheduled emergency days.",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-11",
    "end": "2026-12-12",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Fall 2026 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examinations on Sunday",
    "title_zh": "周日安排期末考试",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-13",
    "end": "",
    "action": "注意：本周日也安排了期末考试，别以为周末就没考试，务必确认自己是否有场次。",
    "desc_en": "Final examinations can be held on this day for the fall 2026 term.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-16",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fees due",
    "title_zh": "学费及杂费缴费截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2026-12-17",
    "end": "",
    "action": "缴费大限！今天前必须缴清学费或完成\"Fees Arranged\"。跨境汇款要留 3-5 个工作日到账，别卡点。",
    "desc_en": "Pay in full or become \"Fees Arranged\" ; payments must be made in sufficient time to arrive on the student account on or before the due date. Notes: A Fees Arranged Extension fee applies after this date. Review Student Financial Services details about tuition due dates , including what happens if changes are made to the student account or fees are posted after this date.",
    "academicYear": 2026
  },
  {
    "title_en": "Opt out of optional/voluntary fees deadline",
    "title_zh": "可选/自愿费用退订截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2026-12-17",
    "end": "",
    "action": "今天前如想退订可选/自愿费用(如某些保险、社团费)，需在 Quest 里操作 opt-out，过期不候。",
    "desc_en": "See how to opt out of optional or voluntary fees in Quest .",
    "academicYear": 2026
  },
  {
    "title_en": "Fees Arranged Extension fees begin",
    "title_zh": "\"费用安排延期\"附加费开始计收",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2026-12-18",
    "end": "",
    "action": "从今天起，未按时缴费/办理费用安排会开始产生延期附加费，尽快处理避免多花钱。",
    "desc_en": "See Student Financial Services website for Fees Arranged Extension fee amounts by date (via the current academic year's schedule of due dates).",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-18",
    "end": "2026-12-19",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Fall 2026 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-20",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the fall 2026 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-21",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term ends",
    "title_zh": "Co-op 实习学期结束",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-23",
    "end": "",
    "action": "Co-op 实习学期结束，实习的同学做好工作交接与实习报告收尾。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-23",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the fall 2026 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Grades begin to appear in Quest",
    "title_zh": "成绩开始在 Quest 显示",
    "category": "成绩",
    "emoji": "📊",
    "priority": 2,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-24",
    "end": "",
    "action": "成绩陆续出分啦！登录 Quest 查看本学期成绩（注意当天不一定全部出齐）。",
    "desc_en": "Registered students can view their unofficial term grades in Quest. Note: Not all grades will be available on this date; instructors submit grades until the grades due deadline published in the Undergraduate Studies Academic Calendar.",
    "academicYear": 2026
  },
  {
    "title_en": "University holiday closure",
    "title_zh": "学校假期闭校",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-24",
    "end": "2026-12-31",
    "action": "学校进入假期闭校，办公室关闭，注意此期间事务无法办理，提前安排好。",
    "desc_en": "No classes and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Apply for Graduation",
    "title_zh": "申请毕业截止",
    "category": "毕业",
    "emoji": "🎓",
    "priority": 3,
    "term_en": "Fall 2026",
    "term_zh": "秋季 2026",
    "start": "2026-12-31",
    "end": "",
    "action": "毕业申请截止！符合毕业条件的同学，今天前务必在 Quest 提交毕业申请，错过要等下一轮。",
    "desc_en": "Deadline for graduate students to apply for graduation in Quest for spring ceremony (degree completion in fall term) .",
    "academicYear": 2026
  },
  {
    "title_en": "University holiday closure",
    "title_zh": "学校假期闭校",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-01",
    "end": "2027-01-03",
    "action": "学校进入假期闭校，办公室关闭，注意此期间事务无法办理，提前安排好。",
    "desc_en": "No classes and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Classes begin",
    "title_zh": "开课 · 学期第一天",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-11",
    "end": "",
    "action": "新学期开课啦！确认课表、上课地点和第一周作业，调好状态开学冲。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable start dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term begins",
    "title_zh": "Co-op 实习学期开始",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-11",
    "end": "",
    "action": "Co-op 实习学期开始，实习的同学按雇主安排入职报到（具体日期以雇主/个人情况为准）。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2027",
    "term_zh": "秋季 2027",
    "start": "2027-01-16",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Fall 2027",
    "term_zh": "秋季 2027",
    "start": "2027-01-23",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Not Fees Arranged (NFA) holds applied",
    "title_zh": "未安排缴费(NFA)冻结生效",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-25",
    "end": "",
    "action": "今天起未完成缴费安排的账户会被加上 NFA 冻结，影响后续选课等操作，尽快把费用处理好。",
    "desc_en": "Not Fees Arranged (NFA) holds are applied to student accounts which are not yet Fees Arranged for the term. Undergraduate students: Find out more about how this hold will impact your course registration process for future terms.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 100%",
    "title_zh": "100% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-29",
    "end": "",
    "action": "今天是全额(100%)退费的最后一天：若打算退课/退学期，今天前操作可拿回全部费用。",
    "desc_en": "Deadline to receive 100% of charges removed for withdrawing from the term, completing degree requirements, or dropping a course. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to arrange tuition and fees",
    "title_zh": "最后办理\"Fees Arranged\"截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-01-31",
    "end": "",
    "action": "最后期限：今天前必须完成学费缴清或办理\"Fees Arranged\"，否则可能被冻结/退课，务必今天搞定。",
    "desc_en": "Refer to tuition and fees deadlines . Late fees apply, see Student Financial Services for details. Visit the Finance website for instructions on submitting a Promissory Note .",
    "academicYear": 2026
  },
  {
    "title_en": "Class drop with grade of Withdrawn, no credit granted (WD)",
    "title_zh": "退课记 WD 期（不计学分）",
    "category": "退课",
    "emoji": "⚠️",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-02",
    "end": "2027-03-28",
    "action": "进入\"退课记 WD\"阶段：此后退课会在成绩单标记 Withdrawn(不计学分)。如要退课请权衡后尽早决定。",
    "desc_en": "During this period, graduate students can continue to drop classes in Quest but a grade of Withdrawn, no credit granted (WD) will be applied and the class will remain on the transcript. Note that WD is not an academic penalty. Outside of this period, students with special circumstances can petition to drop or add a class using a course drop add form (Graduate Studies forms website).",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to select an examination centre or submit a proctor for online course final examinations",
    "title_zh": "线上课程期末：选考点/提交监考人截止",
    "category": "考试",
    "emoji": "📚",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-05",
    "end": "",
    "action": "重要截止：如你有线上课程期末考，今天前必须在系统选好考试中心或提交监考人(proctor)，错过会影响考试！",
    "desc_en": "View details about final examination arrangements for online courses on The Centre website. Deadline is 3 p.m. ET on date listed.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination schedule released",
    "title_zh": "期末考试安排发布",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-05",
    "end": "",
    "action": "期末考试时间表出来啦！登录 Quest 查好每门考试的时间、地点，早做规划。",
    "desc_en": "Visit the Final Examination Schedule website (authentication required) on or after this date to view the term's final examination schedule.",
    "academicYear": 2026
  },
  {
    "title_en": "Reading Week",
    "title_zh": "阅读周 / Reading Week（无课）",
    "category": "假期",
    "emoji": "🎉",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-13",
    "end": "2027-02-21",
    "action": "本周无课！正是赶论文、补作业、复习或好好喘口气的黄金时间，给自己排个计划。",
    "desc_en": "All classes cancelled; offices closed on the weekends and the holiday Monday. Undergraduate students: View the Undergraduate Studies Academic Calendar for more details. Graduate students: View the Graduate Studies Academic Calendar for more details.",
    "academicYear": 2026
  },
  {
    "title_en": "Family Day",
    "title_zh": "家庭日 (Family Day)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-15",
    "end": "",
    "action": "家庭日假期，全校放假，陪陪家人朋友吧～",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 50%",
    "title_zh": "50% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-02-26",
    "end": "",
    "action": "今天是 50% 退费的最后一天：若要退课/退学期，今天前操作还能退回一半费用，之后不退。",
    "desc_en": "Deadline to receive 50% of charges for tuition, co-op fee, and student services fees removed for withdrawing from the term, completing degree requirements, or dropping a course. All other charges remain on student accounts. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Good Friday",
    "title_zh": "耶稣受难日 (Good Friday)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-03-26",
    "end": "",
    "action": "公共假期，全校放假休息。",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Class enrolment period",
    "title_zh": "选课期 (Class Enrolment)",
    "category": "选课",
    "emoji": "📝",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-04-05",
    "end": "2027-05-30",
    "action": "选课期开放！登录 Quest 尽早选好课/调整课表；注意：未办理缴费(Fees Arranged)的同学第3周结束会被系统退课。",
    "desc_en": "During this period, graduate students can enrol themselves in classes using Quest , and can also drop classes in Quest. Graduate students who are not fee arranged and have enrolled in classes will have their classes dropped at the end of the third week of classes (end of class enrolment period).",
    "academicYear": 2026
  },
  {
    "title_en": "Classes end",
    "title_zh": "停课 · 本学期课程结束",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-12",
    "end": "",
    "action": "今天是本学期最后一天上课，收尾好各科笔记和作业，准备进入复习/考试阶段。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable end dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Make-up day for Good Friday",
    "title_zh": "耶稣受难日补课日",
    "category": "补课",
    "emoji": "🔁",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-12",
    "end": "",
    "action": "今天补耶稣受难日缺的课，按对应课表上课。",
    "desc_en": "The loss of a Friday class on March 26 will be made up by following a Friday schedule on Monday, April 12.",
    "academicYear": 2026
  },
  {
    "title_en": "Pre-examination study days",
    "title_zh": "考前复习日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-13",
    "end": "2027-04-14",
    "action": "考前复习日，无课。安心复习，制定好各科的备考计划。",
    "desc_en": "There are one or two study days each term, between the end of the Formal Lecture Period and the beginning of the Final Examination Period. No classes are to be held during study days, except where classes are rescheduled as the result of a campus-wide emergency closure.",
    "academicYear": 2026
  },
  {
    "title_en": "Final Examination Period",
    "title_zh": "期末考试期",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-15",
    "end": "2027-04-30",
    "action": "进入期末考试期，随时核对你的考试安排，合理规划复习节奏。",
    "desc_en": "The Final Examination Period begins on the first date listed, and ends with an emergency day. Students are expected to be available to write their final examination(s) for the entirety of the Final Examination Period, including the scheduled emergency days.",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-16",
    "end": "2027-04-17",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Winter 2027 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-18",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the winter 2027 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-21",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-23",
    "end": "2027-04-24",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Winter 2027 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-25",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the winter 2027 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fees due",
    "title_zh": "学费及杂费缴费截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-04-26",
    "end": "",
    "action": "缴费大限！今天前必须缴清学费或完成\"Fees Arranged\"。跨境汇款要留 3-5 个工作日到账，别卡点。",
    "desc_en": "Pay in full or become \"Fees Arranged\" ; payments must be made in sufficient time to arrive on the student account on or before the due date. Notes: A Fees Arranged Extension fee applies after this date. Review Student Financial Services details about tuition due dates , including what happens if changes are made to the student account or fees are posted after this date.",
    "academicYear": 2026
  },
  {
    "title_en": "Opt out of optional/voluntary fees deadline",
    "title_zh": "可选/自愿费用退订截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-04-26",
    "end": "",
    "action": "今天前如想退订可选/自愿费用(如某些保险、社团费)，需在 Quest 里操作 opt-out，过期不候。",
    "desc_en": "See how to opt out of optional or voluntary fees in Quest .",
    "academicYear": 2026
  },
  {
    "title_en": "Fees Arranged Extension fees begin",
    "title_zh": "\"费用安排延期\"附加费开始计收",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-04-27",
    "end": "",
    "action": "从今天起，未按时缴费/办理费用安排会开始产生延期附加费，尽快处理避免多花钱。",
    "desc_en": "See Student Financial Services website for Fees Arranged Extension fee amounts by date (via the current academic year's schedule of due dates).",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-28",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Apply for Graduation",
    "title_zh": "申请毕业截止",
    "category": "毕业",
    "emoji": "🎓",
    "priority": 3,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-30",
    "end": "",
    "action": "毕业申请截止！符合毕业条件的同学，今天前务必在 Quest 提交毕业申请，错过要等下一轮。",
    "desc_en": "Deadline for graduate students to apply for graduation in Quest for spring ceremony (degree completion in winter term) .",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term ends",
    "title_zh": "Co-op 实习学期结束",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-30",
    "end": "",
    "action": "Co-op 实习学期结束，实习的同学做好工作交接与实习报告收尾。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-04-30",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the winter 2027 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Grades begin to appear in Quest",
    "title_zh": "成绩开始在 Quest 显示",
    "category": "成绩",
    "emoji": "📊",
    "priority": 2,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-05-01",
    "end": "",
    "action": "成绩陆续出分啦！登录 Quest 查看本学期成绩（注意当天不一定全部出齐）。",
    "desc_en": "Registered students can view their unofficial term grades in Quest. Note: Not all grades will be available on this date; instructors submit grades until the grades due deadline published in the Undergraduate Studies Academic Calendar.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-05-03",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Winter 2027",
    "term_zh": "冬季 2027",
    "start": "2027-05-06",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Classes begin",
    "title_zh": "开课 · 学期第一天",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-05-10",
    "end": "",
    "action": "新学期开课啦！确认课表、上课地点和第一周作业，调好状态开学冲。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable start dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term begins",
    "title_zh": "Co-op 实习学期开始",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-05-10",
    "end": "",
    "action": "Co-op 实习学期开始，实习的同学按雇主安排入职报到（具体日期以雇主/个人情况为准）。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "Victoria Day",
    "title_zh": "维多利亚日 (Victoria Day)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-05-24",
    "end": "",
    "action": "公共假期，全校放假休息。",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Not Fees Arranged (NFA) holds applied",
    "title_zh": "未安排缴费(NFA)冻结生效",
    "category": "缴费",
    "emoji": "💰",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-05-25",
    "end": "",
    "action": "今天起未完成缴费安排的账户会被加上 NFA 冻结，影响后续选课等操作，尽快把费用处理好。",
    "desc_en": "Not Fees Arranged (NFA) holds are applied to student accounts which are not yet Fees Arranged for the term. Undergraduate students: Find out more about how this hold will impact your course registration process for future terms.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 100%",
    "title_zh": "100% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-05-31",
    "end": "",
    "action": "今天是全额(100%)退费的最后一天：若打算退课/退学期，今天前操作可拿回全部费用。",
    "desc_en": "Deadline to receive 100% of charges removed for withdrawing from the term, completing degree requirements, or dropping a course. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Class drop with grade of Withdrawn, no credit granted (WD)",
    "title_zh": "退课记 WD 期（不计学分）",
    "category": "退课",
    "emoji": "⚠️",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-01",
    "end": "2027-07-18",
    "action": "进入\"退课记 WD\"阶段：此后退课会在成绩单标记 Withdrawn(不计学分)。如要退课请权衡后尽早决定。",
    "desc_en": "During this period, graduate students can continue to drop classes in Quest but a grade of Withdrawn, no credit granted (WD) will be applied and the class will remain on the transcript. Note that WD is not an academic penalty. Outside of this period, students with special circumstances can petition to drop or add a class using a course drop add form (Graduate Studies forms website).",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to select an examination centre or submit a proctor for online course final examinations",
    "title_zh": "线上课程期末：选考点/提交监考人截止",
    "category": "考试",
    "emoji": "📚",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-04",
    "end": "",
    "action": "重要截止：如你有线上课程期末考，今天前必须在系统选好考试中心或提交监考人(proctor)，错过会影响考试！",
    "desc_en": "View details about final examination arrangements for online courses on The Centre website. Deadline is 3 p.m. ET on date listed.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination schedule released",
    "title_zh": "期末考试安排发布",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-04",
    "end": "",
    "action": "期末考试时间表出来啦！登录 Quest 查好每门考试的时间、地点，早做规划。",
    "desc_en": "Visit the Final Examination Schedule website (authentication required) on or after this date to view the term's final examination schedule.",
    "academicYear": 2026
  },
  {
    "title_en": "Convocation - spring 2027",
    "title_zh": "2027 春季毕业典礼 (Convocation)",
    "category": "毕业",
    "emoji": "🎓",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-15",
    "end": "2027-06-19",
    "action": "春季毕业典礼！毕业生留意典礼时间地点、着装与来宾安排，约上亲友一起见证～",
    "desc_en": "Visit Convocation website for ceremony details.",
    "academicYear": 2026
  },
  {
    "title_en": "Tuition and fee refund deadline - 50%",
    "title_zh": "50% 退费截止",
    "category": "退费",
    "emoji": "💵",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-25",
    "end": "",
    "action": "今天是 50% 退费的最后一天：若要退课/退学期，今天前操作还能退回一半费用，之后不退。",
    "desc_en": "Deadline to receive 50% of charges for tuition, co-op fee, and student services fees removed for withdrawing from the term, completing degree requirements, or dropping a course. All other charges remain on student accounts. See Student Financial Services website .",
    "academicYear": 2026
  },
  {
    "title_en": "Last day to arrange tuition and fees",
    "title_zh": "最后办理\"Fees Arranged\"截止",
    "category": "缴费",
    "emoji": "💰",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-06-30",
    "end": "",
    "action": "最后期限：今天前必须完成学费缴清或办理\"Fees Arranged\"，否则可能被冻结/退课，务必今天搞定。",
    "desc_en": "Refer to tuition and fees deadlines . Late fees apply, see Student Financial Services for details. Visit the Finance website for instructions on submitting a Promissory Note .",
    "academicYear": 2026
  },
  {
    "title_en": "Canada Day",
    "title_zh": "加拿大国庆日 (Canada Day)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-07-01",
    "end": "",
    "action": "加拿大国庆假期，全校放假休息～",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Additional day",
    "title_zh": "额外假日",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-07-02",
    "end": "",
    "action": "今天是学校安排的额外假日，放松一下～",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Civic Holiday",
    "title_zh": "公民假日 (Civic Holiday)",
    "category": "假期",
    "emoji": "🎉",
    "priority": 0,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-02",
    "end": "",
    "action": "全校停课、办公室关闭，今天好好休息一天～",
    "desc_en": "All classes cancelled and offices closed.",
    "academicYear": 2026
  },
  {
    "title_en": "Make-up day for Victoria Day",
    "title_zh": "维多利亚日补课日",
    "category": "补课",
    "emoji": "🔁",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-03",
    "end": "",
    "action": "今天按【周一课表】上课（补维多利亚日缺的课），别走错教室～",
    "desc_en": "The loss of a Monday class on May 24 will be made up by following a Monday schedule on Tuesday, August 3.",
    "academicYear": 2026
  },
  {
    "title_en": "Make-up day for Additional day",
    "title_zh": "额外假日补课日",
    "category": "补课",
    "emoji": "🔁",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-04",
    "end": "",
    "action": "今天补额外假日缺的课，按对应课表上课。",
    "desc_en": "The loss of a Friday class on July 2 will be made up by following a Friday schedule on Wednesday, August 4.",
    "academicYear": 2026
  },
  {
    "title_en": "Classes end",
    "title_zh": "停课 · 本学期课程结束",
    "category": "上课",
    "emoji": "🏫",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-05",
    "end": "",
    "action": "今天是本学期最后一天上课，收尾好各科笔记和作业，准备进入复习/考试阶段。",
    "desc_en": "Laurier may have a different schedule - visit their website for applicable end dates.",
    "academicYear": 2026
  },
  {
    "title_en": "Make-up day for Canada Day",
    "title_zh": "加拿大日补课日",
    "category": "补课",
    "emoji": "🔁",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-05",
    "end": "",
    "action": "今天补加拿大日缺的课，按对应课表上课，留意你的课程安排。",
    "desc_en": "The loss of a Thursday class on July 1 will be made up on Thursday, August 5 (no change in schedule).",
    "academicYear": 2026
  },
  {
    "title_en": "Pre-examination study days",
    "title_zh": "考前复习日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-06",
    "end": "",
    "action": "考前复习日，无课。安心复习，制定好各科的备考计划。",
    "desc_en": "There are one or two study days each term, between the end of the Formal Lecture Period and the beginning of the Final Examination Period. No classes are to be held during study days, except where classes are rescheduled as the result of a campus-wide emergency closure.",
    "academicYear": 2026
  },
  {
    "title_en": "Final Examination Period",
    "title_zh": "期末考试期",
    "category": "考试",
    "emoji": "📚",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-09",
    "end": "2027-08-21",
    "action": "进入期末考试期，随时核对你的考试安排，合理规划复习节奏。",
    "desc_en": "The Final Examination Period begins on the first date listed, and ends with an emergency day. Students are expected to be available to write their final examination(s) for the entirety of the Final Examination Period, including the scheduled emergency days.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-11",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-13",
    "end": "2027-08-14",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Spring 2027 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-15",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the spring 2027 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-18",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Co-operative work term ends",
    "title_zh": "Co-op 实习学期结束",
    "category": "Co-op",
    "emoji": "💼",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-20",
    "end": "",
    "action": "Co-op 实习学期结束，实习的同学做好工作交接与实习报告收尾。",
    "desc_en": "Actual dates may vary depending on employer or student requirements.",
    "academicYear": 2026
  },
  {
    "title_en": "In-person final examination days for online courses",
    "title_zh": "线上课程·线下期末考试日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-20",
    "end": "",
    "action": "线上课程的线下期末考试日，如你有线上课程，确认考点与到场安排。",
    "desc_en": "Spring 2027 term dates; not all dates may be used.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination emergency days",
    "title_zh": "期末考试应急日",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-21",
    "end": "",
    "action": "应急预留日：若学校因故关闭，考试会顺延到这些日子，保持关注官方通知。",
    "desc_en": "Dates reserved to hold final examinations in the event the University is closed during the spring 2027 Final Examination Period: Examinations will be rescheduled on the next available day, including Sunday, on which examinations have not been scheduled.",
    "academicYear": 2026
  },
  {
    "title_en": "Grades begin to appear in Quest",
    "title_zh": "成绩开始在 Quest 显示",
    "category": "成绩",
    "emoji": "📊",
    "priority": 2,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-22",
    "end": "",
    "action": "成绩陆续出分啦！登录 Quest 查看本学期成绩（注意当天不一定全部出齐）。",
    "desc_en": "Registered students can view their unofficial term grades in Quest. Note: Not all grades will be available on this date; instructors submit grades until the grades due deadline published in the Undergraduate Studies Academic Calendar.",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-23",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Final examination make-up sessions",
    "title_zh": "期末考试补考场次",
    "category": "考试",
    "emoji": "📚",
    "priority": 1,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-26",
    "end": "",
    "action": "今天是期末补考/顺延场次，如与你相关请确认时间地点。",
    "desc_en": "Each term, the Office of the Registrar provides instructors with several dates and times during the Final Examination Period, or shortly thereafter, at which they can register a student to write their deferred final examination. The registration process to attend will only occur after the student and the instructor have mutually agreed on the date and time. Any student who arrives to a make-up final examination session who is not registered to write at that session will not be permitted to write and will be directed to contact their instructor. Final examination make-up sessions are only available at the University of Waterloo campus",
    "academicYear": 2026
  },
  {
    "title_en": "Apply for Graduation",
    "title_zh": "申请毕业截止",
    "category": "毕业",
    "emoji": "🎓",
    "priority": 3,
    "term_en": "Spring 2027",
    "term_zh": "春季 2027",
    "start": "2027-08-31",
    "end": "",
    "action": "毕业申请截止！符合毕业条件的同学，今天前务必在 Quest 提交毕业申请，错过要等下一轮。",
    "desc_en": "Deadline for graduate students to apply for graduation in Quest for fall ceremony (degree completion in spring term) .",
    "academicYear": 2026
  }
];
