// Auto-generated from the verified accommodation report dataset (2026-08-19 snapshot).
// 50 candidates. window.ACCOM is consumed by app.js. Do not edit by hand.
window.ACCOM = [
 {
  "name": "Kitchener Motel",
  "city": "Kitchener",
  "type": "汽车旅馆",
  "bf": "N",
  "addr": "1485 Victoria St N",
  "phone": "+1 519-745-1177 / 1-800-574-2156",
  "email": null,
  "web": "kitchenermotel.ca",
  "url": "http://www.kitchenermotel.ca",
  "pub": "$59–75/晚（周/冬特价另议）",
  "neg": "$50/晚",
  "tgt": "$48/晚",
  "cost27": "$1,350",
  "mo": "$450",
  "monthly": 450,
  "ls": "高（周价/小厨房套房/21翻新房）",
  "score": 89.0,
  "tier": "A",
  "rating": "6.6/10",
  "rating_note": "Booking·83条 · 便宜老旧、隔音差，位置便利",
  "rank": 1
 },
 {
  "name": "Staybridge Suites Waterloo",
  "city": "Waterloo",
  "type": "延长住宿公寓酒店",
  "bf": "Y",
  "addr": "10 Benjamin Rd",
  "phone": "+1 519-514-5500",
  "email": "sbswaterloosj@wgroup.ca",
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$105–174/晚",
  "neg": "$100/晚",
  "tgt": "$90/晚",
  "cost27": "$2,700",
  "mo": "$900",
  "monthly": 900,
  "ls": "高（全厨/洗衣/周价）",
  "score": 84.5,
  "tier": "A",
  "rating": "8.8/10",
  "rating_note": "IHG/Google·285条 · 全新干净、套房带厨房",
  "rank": 2
 },
 {
  "name": "Kijiji 家具房（KW 挂牌）",
  "city": "KW",
  "type": "私人房/地下室",
  "bf": "N",
  "addr": "平台挂牌分布",
  "phone": "平台消息",
  "email": null,
  "web": "kijiji.ca",
  "url": "https://www.google.com/search?q=site%3Akijiji.ca+kitchener+waterloo+furnished+room+for+rent",
  "pub": "$590–850/月",
  "neg": "$620/月",
  "tgt": "$550/月",
  "cost27": "按月计",
  "mo": "$620",
  "monthly": 620,
  "ls": "高（真房间/可现金谈）",
  "score": 84.0,
  "tier": "A",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 3
 },
 {
  "name": "Airbnb 月租私人房（KW）",
  "city": "KW",
  "type": "民宿私人房",
  "bf": "N",
  "addr": "平台挂牌分布",
  "phone": "平台消息",
  "email": null,
  "web": "airbnb.ca",
  "url": "https://www.airbnb.ca/s/Kitchener--Ontario/homes",
  "pub": "$700–1,000/月",
  "neg": "$700/月",
  "tgt": "$650/月",
  "cost27": "按月计",
  "mo": "$700",
  "monthly": 700,
  "ls": "高（房东直谈）",
  "score": 84.0,
  "tier": "A",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 4
 },
 {
  "name": "Roomies.ca / Qdb 家具房",
  "city": "KW/Guelph",
  "type": "私人房",
  "bf": "N",
  "addr": "平台挂牌分布",
  "phone": "平台消息",
  "email": null,
  "web": "roomies.ca / qdb.ca",
  "url": "https://www.roomies.ca",
  "pub": "$600–900/月",
  "neg": "$700/月",
  "tgt": "$650/月",
  "cost27": "按月计",
  "mo": "$700",
  "monthly": 700,
  "ls": "高（月付灵活）",
  "score": 84.0,
  "tier": "A",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 5
 },
 {
  "name": "Quality Inn Kitchener",
  "city": "Kitchener",
  "type": "经济酒店",
  "bf": "Y",
  "addr": "2899 King St E",
  "phone": "+1 519-894-3500",
  "email": null,
  "web": "choicehotels.com",
  "url": "https://www.choicehotels.com",
  "pub": "$51–120/晚（典型 ~$106）",
  "neg": "$55/晚",
  "tgt": "$52/晚",
  "cost27": "$1,485",
  "mo": "$495",
  "monthly": 495,
  "ls": "中（业主可谈/含早）",
  "score": 82.8,
  "tier": "A",
  "rating": "8.0/10",
  "rating_note": "TripAdvisor·383条 · 含早好评、近高速，房间略旧",
  "rank": 6
 },
 {
  "name": "Howard Johnson Kitchener (Conestoga)",
  "city": "Kitchener",
  "type": "经济酒店",
  "bf": "Y",
  "addr": "1333 Weber St E",
  "phone": "+1 519-893-1234 (预订 1-800-219-2797)",
  "email": null,
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$90–100/晚（明示长期折扣）",
  "neg": "$75/晚",
  "tgt": "$70/晚",
  "cost27": "$2,025",
  "mo": "$675",
  "monthly": 675,
  "ls": "高（明示 Group/企业/长住折扣）",
  "score": 81.8,
  "tier": "A",
  "rating": "5.2/10",
  "rating_note": "Booking·386条 · 陈旧脏乱、烟味、维护差 ⚠",
  "rank": 7
 },
 {
  "name": "Knights Inn Kitchener (Weber Inn)",
  "city": "Kitchener",
  "type": "汽车旅馆/长住",
  "bf": "Y",
  "addr": "1455 Weber St E",
  "phone": "+1 519-893-6641",
  "email": null,
  "web": null,
  "url": null,
  "pub": "≈$91/晚（长住价可谈）",
  "neg": "$80/晚",
  "tgt": "$70/晚",
  "cost27": "$2,160",
  "mo": "$720",
  "monthly": 720,
  "ls": "高（效率房全厨/明示长住价）",
  "score": 81.8,
  "tier": "A",
  "rating": "6.0/10",
  "rating_note": "TripAdvisor·130条 · 床品尚可、设施旧、长住客混杂 ⚠",
  "rank": 8
 },
 {
  "name": "Private furnished room · Downtown Kitchener",
  "city": "Kitchener",
  "type": "私人房",
  "bf": "N",
  "addr": "George/Duke St W 一带",
  "phone": "Roomies.ca",
  "email": null,
  "web": null,
  "url": null,
  "pub": "$650–800/月",
  "neg": "$725/月",
  "tgt": "$650/月",
  "cost27": "按月计",
  "mo": "$725",
  "monthly": 725,
  "ls": "高（月付/近市中心）",
  "score": 81.8,
  "tier": "A",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 9
 },
 {
  "name": "Travelodge by Wyndham Cambridge-Waterloo",
  "city": "Cambridge",
  "type": "经济汽车旅馆",
  "bf": "Y",
  "addr": "605 Hespeler Rd",
  "phone": "+1 519-622-1180",
  "email": null,
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$44–140/晚（淡旺差大）",
  "neg": "$60/晚",
  "tgt": "$55/晚",
  "cost27": "$1,620",
  "mo": "$540",
  "monthly": 540,
  "ls": "高（小厨房/周价可谈/免费停车）",
  "score": 81.2,
  "tier": "A",
  "rating": "5.6/10",
  "rating_note": "Google·525条 · 设施破旧、卫生差、有异味 ⚠",
  "rank": 10
 },
 {
  "name": "Super 8 by Wyndham Cambridge",
  "city": "Cambridge",
  "type": "经济汽车旅馆",
  "bf": "Y",
  "addr": "650 Hespeler Rd",
  "phone": "+1 519-622-1070",
  "email": null,
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$44–90/晚",
  "neg": "$58/晚",
  "tgt": "$55/晚",
  "cost27": "$1,566",
  "mo": "$522",
  "monthly": 522,
  "ls": "高（冰箱/微炉/周价）",
  "score": 80.2,
  "tier": "A",
  "rating": "6.1/10",
  "rating_note": "Booking·354条 · 脏、异味、设施失修 ⚠",
  "rank": 11
 },
 {
  "name": "Travelodge Guelph (Royal Inn & Suites)",
  "city": "Guelph",
  "type": "独立/长住旅店",
  "bf": "Y",
  "addr": "106 Carden St",
  "phone": "+1 519-835-1331",
  "email": null,
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$90–130/晚（典型 ~$100）",
  "neg": "$85/晚",
  "tgt": "$75/晚",
  "cost27": "$2,295",
  "mo": "$765",
  "monthly": 765,
  "ls": "高（公寓式长租单元）",
  "score": 80.0,
  "tier": "A",
  "rating": "4.0/10",
  "rating_note": "TripAdvisor·22条 · 破旧、卫生差、邻夜店噪音 ⚠⚠",
  "rank": 12
 },
 {
  "name": "Boardwalk Homes · Executive Guest Rooms",
  "city": "Kitchener",
  "type": "家具延长住宿",
  "bf": "N",
  "addr": "University Ave & Fischer-Hallman",
  "phone": "平台/网站",
  "email": null,
  "web": "Boardwalk Homes",
  "url": "https://www.google.com/search?q=Boardwalk+Homes+Kitchener+furnished+suites",
  "pub": "~$81/晚均",
  "neg": "$81/晚",
  "tgt": "$75/晚",
  "cost27": "$2,187",
  "mo": "$729",
  "monthly": 729,
  "ls": "高（家具套房/含停车WiFi）",
  "score": 79.5,
  "tier": "A",
  "rating": "7.5/10",
  "rating_note": "KAYAK·146条 · 厨房齐全适合长住；管理松散偶有噪音",
  "rank": 13
 },
 {
  "name": "Comfort Inn Cambridge – Hwy 401",
  "city": "Cambridge",
  "type": "经济酒店",
  "bf": "Y",
  "addr": "220 Holiday Inn Dr",
  "phone": "+1 519-658-1100",
  "email": null,
  "web": "choicehotels.com",
  "url": "https://www.choicehotels.com",
  "pub": "$68–158/晚",
  "neg": "$65/晚",
  "tgt": "$60/晚",
  "cost27": "$1,755",
  "mo": "$585",
  "monthly": 585,
  "ls": "中（含早/泳池/冰箱微炉）",
  "score": 79.2,
  "tier": "A",
  "rating": "7.3/10",
  "rating_note": "Booking·663条 · 员工友好；建筑老化、偶有烟味",
  "rank": 14
 },
 {
  "name": "London House B&B Guelph",
  "city": "Guelph",
  "type": "民宿 B&B",
  "bf": "Y",
  "addr": "80 London Road W",
  "phone": "+1 519-824-6874 / 1-877-836-6874",
  "email": null,
  "web": "bbcanada.com/588",
  "url": "https://www.bbcanada.com/588",
  "pub": "$70–179/晚（月租40%off）",
  "neg": "$85/晚",
  "tgt": "$75/晚",
  "cost27": "$2,295",
  "mo": "$765",
  "monthly": 765,
  "ls": "极高（7/14/21天+月租阶梯折扣）",
  "score": 79.2,
  "tier": "A",
  "rating": "10/10",
  "rating_note": "TripAdvisor·104条 · 房东热情、早餐好、贵湖B&B第1名",
  "rank": 15
 },
 {
  "name": "Best Western Plus Waterloo",
  "city": "Waterloo",
  "type": "中端酒店",
  "bf": "Y",
  "addr": "547 King St N",
  "phone": "+1 519-884-0100",
  "email": null,
  "web": "bestwestern.com",
  "url": "https://www.bestwestern.com",
  "pub": "$109–125/晚",
  "neg": "$85/晚",
  "tgt": "$75/晚",
  "cost27": "$2,295",
  "mo": "$765",
  "monthly": 765,
  "ls": "中高（含早/停车/部分小厨）",
  "score": 79.0,
  "tier": "A",
  "rating": "8.2/10",
  "rating_note": "Expedia·988条 · 干净、早餐佳、近商场",
  "rank": 16
 },
 {
  "name": "Homewood Suites Waterloo",
  "city": "Waterloo",
  "type": "延长住宿公寓酒店",
  "bf": "Y",
  "addr": "45 Benjamin Rd",
  "phone": "+1 519-514-0088",
  "email": null,
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$111–180/晚（典型 ~$138）",
  "neg": "$105/晚",
  "tgt": "$95/晚",
  "cost27": "$2,835",
  "mo": "$945",
  "monthly": 945,
  "ls": "高（全厨/含早）",
  "score": 79.0,
  "tier": "A",
  "rating": "8.9/10",
  "rating_note": "Trivago·3603条 · 员工好含早；清洁度参差、隔音差",
  "rank": 17
 },
 {
  "name": "Mayflower Motel",
  "city": "Kitchener",
  "type": "汽车旅馆",
  "bf": "N",
  "addr": "1189 Victoria St N",
  "phone": "+1 519-404-3395",
  "email": null,
  "web": null,
  "url": null,
  "pub": "~$62–85/晚",
  "neg": "$58/晚",
  "tgt": "$55/晚",
  "cost27": "$1,566",
  "mo": "$522",
  "monthly": 522,
  "ls": "中（路边预算/冰箱微炉）",
  "score": 78.5,
  "tier": "A",
  "rating": "7.3/10",
  "rating_note": "Booking·132条 · 员工友好、较干净、性价比高",
  "rank": 18
 },
 {
  "name": "Home2 Suites Kitchener",
  "city": "Kitchener",
  "type": "延长住宿酒店",
  "bf": "Y",
  "addr": "30 Fairway Rd S",
  "phone": "+1 519-489-2040",
  "email": null,
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$99–150/晚",
  "neg": "$90/晚",
  "tgt": "$80/晚",
  "cost27": "$2,430",
  "mo": "$810",
  "monthly": 810,
  "ls": "高（小厨/含早/洗衣）",
  "score": 78.2,
  "tier": "A",
  "rating": "8.7/10",
  "rating_note": "Trip.com·120条 · 新且干净、套房宽敞、早餐好",
  "rank": 19
 },
 {
  "name": "Cambridge Hotel & Conference Centre",
  "city": "Cambridge",
  "type": "独立酒店",
  "bf": "Y",
  "addr": "700 Hespeler Rd",
  "phone": "+1 519-622-1505",
  "email": "info@cambridgehotel.ca",
  "web": "cambridgehotel.ca",
  "url": "https://www.cambridgehotel.ca",
  "pub": "$101–175/晚（典型 ~$160）",
  "neg": "$95/晚",
  "tgt": "$85/晚",
  "cost27": "$2,565",
  "mo": "$855",
  "monthly": 855,
  "ls": "高（小厨套房/Jacuzzi/具名销售）",
  "score": 77.8,
  "tier": "A",
  "rating": "8.4/10",
  "rating_note": "Google·1582条 · 服务好、含早、房间干净",
  "rank": 20
 },
 {
  "name": "Homewood Suites by Hilton Cambridge-Waterloo",
  "city": "Cambridge",
  "type": "延长住宿公寓酒店",
  "bf": "Y",
  "addr": "800 Jamieson Pkwy",
  "phone": "+1 519-651-2888",
  "email": null,
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$102–266/晚（典型 ~$220）",
  "neg": "$110/晚",
  "tgt": "$100/晚",
  "cost27": "$2,970",
  "mo": "$990",
  "monthly": 990,
  "ls": "高（全厨/含早/泳池）",
  "score": 76.0,
  "tier": "A",
  "rating": "8.8/10",
  "rating_note": "Trip.com·103条 · 套房大带厨房含早；泳池常关",
  "rank": 21
 },
 {
  "name": "Crowne Plaza Kitchener",
  "city": "Kitchener",
  "type": "中端全服务",
  "bf": "Y",
  "addr": "105 King St E",
  "phone": "+1 519-744-4141",
  "email": null,
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$85–152/晚",
  "neg": "$90/晚",
  "tgt": "$80/晚",
  "cost27": "$2,430",
  "mo": "$810",
  "monthly": 810,
  "ls": "中高（部分小厨/含早/市中心）",
  "score": 74.0,
  "tier": "A",
  "rating": "8.2/10",
  "rating_note": "Trip.com·126条 · 位置佳早餐好；房间偏旧、停车收费",
  "rank": 22
 },
 {
  "name": "Frederick Street Inn (B&B)",
  "city": "Kitchener",
  "type": "民宿 B&B(市中心)",
  "bf": "Y",
  "addr": "230 Frederick St",
  "phone": "+1 519-745-2060",
  "email": null,
  "web": "frederickstreetinn.ca",
  "url": "http://www.frederickstreetinn.ca",
  "pub": "~$100+/晚",
  "neg": "$110/晚",
  "tgt": "$100/晚",
  "cost27": "$2,970",
  "mo": "$990",
  "monthly": 990,
  "ls": "高（明示 Long Term Stay 套餐）",
  "score": 73.0,
  "tier": "A",
  "rating": "9.5/10",
  "rating_note": "Booking·157条 · 老宅含早、主人热情，偶有街噪",
  "rank": 23
 },
 {
  "name": "Embassy Motel Kitchener",
  "city": "Kitchener",
  "type": "汽车旅馆",
  "bf": "N",
  "addr": "4521 King St E",
  "phone": "+1 519-653-3176",
  "email": null,
  "web": null,
  "url": null,
  "pub": "从 $75/晚",
  "neg": "$72/晚",
  "tgt": "$68/晚",
  "cost27": "$1,944",
  "mo": "$648",
  "monthly": 648,
  "ls": "中低（东King街/翻新）",
  "score": 71.8,
  "tier": "A",
  "rating": "7.9/10",
  "rating_note": "KAYAK·37条 · 干净简洁、员工友好，个别噪音",
  "rank": 24
 },
 {
  "name": "Holiday Inn Express Waterloo (St. Jacobs)",
  "city": "Waterloo",
  "type": "中端有限服务",
  "bf": "Y",
  "addr": "14 Benjamin Rd",
  "phone": "+1 519-772-9800",
  "email": "hiexwaterloosj@wgroup.ca",
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$125–182/晚",
  "neg": "$115/晚",
  "tgt": "$100/晚",
  "cost27": "$3,105",
  "mo": "$1,035",
  "monthly": 1035,
  "ls": "中（冰箱微炉/含早/泳池）",
  "score": 71.5,
  "tier": "A",
  "rating": "9.0/10",
  "rating_note": "TripAdvisor·431条 · 家庭友好、早餐赞、泳池受欢迎",
  "rank": 25
 },
 {
  "name": "Holiday Inn Express & Suites Guelph",
  "city": "Guelph",
  "type": "中端有限服务",
  "bf": "Y",
  "addr": "540 Silvercreek Pkwy N",
  "phone": "+1 519-824-2400",
  "email": "hiexpressguelph@wgroup.ca",
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$115–170/晚",
  "neg": "$115/晚",
  "tgt": "$100/晚",
  "cost27": "$3,105",
  "mo": "$1,035",
  "monthly": 1035,
  "ls": "中高（小厨/含早）",
  "score": 71.5,
  "tier": "A",
  "rating": "8.0/10",
  "rating_note": "TripAdvisor·198条 · 干净含早；部分平台已更名 Spark by Hilton，订前确认",
  "rank": 26
 },
 {
  "name": "Super 8 by Wyndham Guelph",
  "city": "Guelph",
  "type": "经济汽车旅馆",
  "bf": "Y",
  "addr": "281 Woodlawn Rd W",
  "phone": "+1 519-836-5850",
  "email": "super8.guelph@rogers.com",
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$100–149/晚（典型 ~$115）",
  "neg": "$90/晚",
  "tgt": "$80/晚",
  "cost27": "$2,430",
  "mo": "$810",
  "monthly": 810,
  "ls": "中（冰箱微炉/周中低需）",
  "score": 71.2,
  "tier": "A",
  "rating": "6.5/10",
  "rating_note": "Booking·310条 · 便宜员工好；墙薄噪音、地毯破损",
  "rank": 27
 },
 {
  "name": "Best Western Plus Royal Brock Guelph",
  "city": "Guelph",
  "type": "中端酒店",
  "bf": "Y",
  "addr": "716 Gordon St",
  "phone": "+1 519-836-1240",
  "email": null,
  "web": "bestwestern.com",
  "url": "https://www.bestwestern.com",
  "pub": "$95–176/晚（典型 ~$127）",
  "neg": "$90/晚",
  "tgt": "$80/晚",
  "cost27": "$2,430",
  "mo": "$810",
  "monthly": 810,
  "ls": "中（冰箱微炉/周月可谈）",
  "score": 71.0,
  "tier": "A",
  "rating": "7.8/10",
  "rating_note": "Booking·309条 · 早餐好、近大学；设施旧",
  "rank": 28
 },
 {
  "name": "Best Western Plus Cambridge Hotel",
  "city": "Cambridge",
  "type": "中端酒店",
  "bf": "Y",
  "addr": "730 Old Hespeler Rd",
  "phone": "+1 519-623-4600",
  "email": null,
  "web": "bestwestern.com",
  "url": "https://www.bestwestern.com",
  "pub": "$90–176/晚（典型 ~$130）",
  "neg": "$95/晚",
  "tgt": "$85/晚",
  "cost27": "$2,565",
  "mo": "$855",
  "monthly": 855,
  "ls": "中高（小厨房/含早）",
  "score": 71.0,
  "tier": "A",
  "rating": "7.6/10",
  "rating_note": "Booking·994条 · 早餐好员工好；设施旧",
  "rank": 29
 },
 {
  "name": "Staybridge Suites Guelph",
  "city": "Guelph",
  "type": "延长住宿公寓酒店",
  "bf": "Y",
  "addr": "11 Corporate Ct",
  "phone": "+1 519-767-3300",
  "email": "reservations@sbguelph.com",
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$170–285/晚",
  "neg": "$200/晚",
  "tgt": "$180/晚",
  "cost27": "$5,400",
  "mo": "$1,800",
  "monthly": 1800,
  "ls": "高（全厨/含早/晚间社交）",
  "score": 70.5,
  "tier": "A",
  "rating": "9.0/10",
  "rating_note": "TripAdvisor·351条 · 套房大带厨房、安静（贵湖第1名）",
  "rank": 30
 },
 {
  "name": "Days Inn by Wyndham Guelph",
  "city": "Guelph",
  "type": "经济酒店",
  "bf": "Y",
  "addr": "785 Gordon St",
  "phone": "+1 519-822-9112 (团体 1-800-906-2871)",
  "email": null,
  "web": "wyndhamhotels.com",
  "url": "https://www.wyndhamhotels.com",
  "pub": "$125–170/晚",
  "neg": "$90/晚",
  "tgt": "$80/晚",
  "cost27": "$2,430",
  "mo": "$810",
  "monthly": 810,
  "ls": "中（近UofG/含早/冰箱微炉）",
  "score": 70.0,
  "tier": "A",
  "rating": "7.0/10",
  "rating_note": "TripAdvisor·584条 · 便宜近大学；设施旧、卫生参差",
  "rank": 31
 },
 {
  "name": "Holiday Inn Express Kitchener SE",
  "city": "Kitchener",
  "type": "中端有限服务",
  "bf": "Y",
  "addr": "4355 King St E",
  "phone": "+1 519-650-6090",
  "email": "frontdesk@hiexkitchener.ca",
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "$130–179/晚（典型 ~$149）",
  "neg": "$115/晚",
  "tgt": "$100/晚",
  "cost27": "$3,105",
  "mo": "$1,035",
  "monthly": 1035,
  "ls": "中（冰箱微炉/含早）",
  "score": 70.0,
  "tier": "A",
  "rating": "8.8/10",
  "rating_note": "Trip.com·113条 · 新装修很干净、早餐丰富",
  "rank": 32
 },
 {
  "name": "Comfort Inn Waterloo",
  "city": "Waterloo",
  "type": "经济酒店",
  "bf": "?",
  "addr": "190 Weber St N",
  "phone": "+1 519-747-9400",
  "email": null,
  "web": "choicehotels.com",
  "url": "https://www.choicehotels.com",
  "pub": "US$79–130/晚（典型 ~C$93）",
  "neg": "$102/晚",
  "tgt": "$90/晚",
  "cost27": "$2,754",
  "mo": "$918",
  "monthly": 918,
  "ls": "中（无厨房）",
  "score": 69.2,
  "tier": "B",
  "rating": "7.0/10",
  "rating_note": "TripAdvisor·271条 · 性价比尚可；隔音差、个别霉味",
  "rank": 33
 },
 {
  "name": "Sunbridge Hotel & Conference Centre",
  "city": "Cambridge",
  "type": "独立酒店",
  "bf": "N",
  "addr": "200 Holiday Inn Dr",
  "phone": "+1 519-658-4601",
  "email": null,
  "web": null,
  "url": null,
  "pub": "$99–170/晚",
  "neg": "$110/晚",
  "tgt": "$100/晚",
  "cost27": "$2,970",
  "mo": "$990",
  "monthly": 990,
  "ls": "中（小厨套房/企业折扣）",
  "score": 69.2,
  "tier": "B",
  "rating": "7.3/10",
  "rating_note": "Booking·216条 · 房间大泳池好；设施旧、门锁差",
  "rank": 34
 },
 {
  "name": "Hotel Laurier (WLU)",
  "city": "Waterloo",
  "type": "大学私人房",
  "bf": "?",
  "addr": "200 King St N",
  "phone": "+1 519-884-0710 / 548-889-3249",
  "email": "hotel@wlu.ca",
  "web": "wlu.ca/hotel-laurier",
  "url": "https://www.wlu.ca",
  "pub": "$40–220/晚（私人房）",
  "neg": "$100/晚",
  "tgt": "$90/晚",
  "cost27": "$2,700",
  "mo": "$900",
  "monthly": 900,
  "ls": "中（校内/有私房/灵活）",
  "score": 69.0,
  "tier": "B",
  "rating": "6.0/10",
  "rating_note": "TripAdvisor·11条 · 便宜位置好；宿舍式设施简陋 ⚠",
  "rank": 35
 },
 {
  "name": "Green Gables Guest House (B&B)",
  "city": "Kitchener",
  "type": "民宿 B&B",
  "bf": "Y",
  "addr": "189 Queen St N",
  "phone": "+1 519-579-5539",
  "email": null,
  "web": "greengablesguesthouse.ca",
  "url": "http://www.greengablesguesthouse.ca",
  "pub": "~$100+/晚",
  "neg": "$110/晚",
  "tgt": "$100/晚",
  "cost27": "$2,970",
  "mo": "$990",
  "monthly": 990,
  "ls": "中（可谈长住）",
  "score": 68.3,
  "tier": "B",
  "rating": "9.6/10",
  "rating_note": "Google·17条 · 老宅主人热情含早；停车位有限",
  "rank": 36
 },
 {
  "name": "Waterloo Inn (Inn of Waterloo)",
  "city": "Waterloo",
  "type": "中端酒店",
  "bf": "?",
  "addr": "475 King St N",
  "phone": "+1 519-884-0220 / 804-1130",
  "email": null,
  "web": null,
  "url": null,
  "pub": "$107–159/晚",
  "neg": "$112/晚",
  "tgt": "$100/晚",
  "cost27": "$3,024",
  "mo": "$1,008",
  "monthly": 1008,
  "ls": "中（新重开/可谈）",
  "score": 68.0,
  "tier": "B",
  "rating": "7.3/10",
  "rating_note": "KAYAK·1247条 · 位置好泳池受欢迎；设施旧、个别卫生差评 ⚠",
  "rank": 37
 },
 {
  "name": "Walper Hotel Kitchener",
  "city": "Kitchener",
  "type": "精品酒店(市中心)",
  "bf": "?",
  "addr": "20 Queen St S",
  "phone": "+1 519-745-4321",
  "email": null,
  "web": "thewalper.com",
  "url": "https://thewalper.com",
  "pub": "$109–187/晚",
  "neg": "$102/晚",
  "tgt": "$95/晚",
  "cost27": "$2,754",
  "mo": "$918",
  "monthly": 918,
  "ls": "中低（精品/包段意愿弱）",
  "score": 67.0,
  "tier": "B",
  "rating": "8.8/10",
  "rating_note": "Google·1406条 · 历史精品、位置员工极佳；停车难收费",
  "rank": 38
 },
 {
  "name": "Holiday Inn Guelph Hotel & Conference Centre",
  "city": "Guelph",
  "type": "中端全服务",
  "bf": "?",
  "addr": "601 Scottsdale Dr",
  "phone": "+1 519-836-0231",
  "email": null,
  "web": "ihg.com",
  "url": "https://www.ihg.com",
  "pub": "~$120–180/晚",
  "neg": "$120/晚",
  "tgt": "$105/晚",
  "cost27": "$3,240",
  "mo": "$1,080",
  "monthly": 1080,
  "ls": "中（近UofG）",
  "score": 66.0,
  "tier": "B",
  "rating": "8.0/10",
  "rating_note": "TripAdvisor·349条 · 员工友好泳池受欢迎；设施老化",
  "rank": 39
 },
 {
  "name": "Hampton Inn & Suites by Hilton Guelph",
  "city": "Guelph",
  "type": "中端有限服务",
  "bf": "Y",
  "addr": "725 Imperial Rd N",
  "phone": "+1 519-821-2144",
  "email": null,
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$143–200/晚",
  "neg": "$130/晚",
  "tgt": "$115/晚",
  "cost27": "$3,510",
  "mo": "$1,170",
  "monthly": 1170,
  "ls": "中（含早/小厨/泳池）",
  "score": 66.0,
  "tier": "B",
  "rating": "8.4/10",
  "rating_note": "Booking·306条 · 干净含早员工好；热水浴缸常坏",
  "rank": 40
 },
 {
  "name": "Hilton Garden Inn Cambridge",
  "city": "Cambridge",
  "type": "中端全服务",
  "bf": "N",
  "addr": "746 Old Hespeler Rd",
  "phone": "+1 519-620-8936",
  "email": "YYZCM_GM@hilton.com",
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$130–160/晚（典型 ~$152）",
  "neg": "$120/晚",
  "tgt": "$105/晚",
  "cost27": "$3,240",
  "mo": "$1,080",
  "monthly": 1080,
  "ls": "中（位置偏/无早）",
  "score": 65.2,
  "tier": "B",
  "rating": "8.0/10",
  "rating_note": "Google·952条 · 干净位置好服务佳；早餐另收费",
  "rank": 41
 },
 {
  "name": "Courtyard Waterloo St. Jacobs",
  "city": "Waterloo",
  "type": "中端有限服务",
  "bf": "?",
  "addr": "50 Benjamin Rd E",
  "phone": "+1 519-884-9295 (销售 884-1426)",
  "email": null,
  "web": "marriott.com",
  "url": "https://www.marriott.com",
  "pub": "$135–149/晚",
  "neg": "$125/晚",
  "tgt": "$110/晚",
  "cost27": "$3,375",
  "mo": "$1,125",
  "monthly": 1125,
  "ls": "中（销售联系/无厨房）",
  "score": 65.0,
  "tier": "B",
  "rating": "8.8/10",
  "rating_note": "Marriott·1014条 · 干净安静服务好",
  "rank": 42
 },
 {
  "name": "DoubleTree by Hilton Kitchener",
  "city": "Kitchener",
  "type": "中端全服务",
  "bf": "?",
  "addr": "30 Fairway Rd S",
  "phone": "+1 519-893-1211",
  "email": "YHMCM_DT_Hotel@hilton.com",
  "web": "hilton.com",
  "url": "https://www.hilton.com",
  "pub": "$152–178/晚（典型 ~$158）",
  "neg": "$140/晚",
  "tgt": "$125/晚",
  "cost27": "$3,780",
  "mo": "$1,260",
  "monthly": 1260,
  "ls": "中（无厨房/偏贵）",
  "score": 65.0,
  "tier": "B",
  "rating": "8.5/10",
  "rating_note": "Trip.com·108条 · 翻新后干净现代；偶有清洁疏漏",
  "rank": 43
 },
 {
  "name": "Forest Hill Bed & Breakfast",
  "city": "Kitchener",
  "type": "民宿 B&B",
  "bf": "Y",
  "addr": "78 Forest Hill Dr",
  "phone": "+1 519-748-9403",
  "email": null,
  "web": "foresthillbandb.com",
  "url": "http://www.foresthillbandb.com",
  "pub": "$115–130/晚 +HST",
  "neg": "$115/晚",
  "tgt": "$105/晚",
  "cost27": "$3,105",
  "mo": "$1,035",
  "monthly": 1035,
  "ls": "中低（住宅区/超预算）",
  "score": 63.5,
  "tier": "B",
  "rating": "9.7/10",
  "rating_note": "Trip.com·40条 · 主人热情、套房极干净、早餐佳",
  "rank": 44
 },
 {
  "name": "City Casa / Nest 行政套房",
  "city": "KW",
  "type": "企业服务公寓(整租)",
  "bf": "N",
  "addr": "市中心公寓",
  "phone": "网站表单",
  "email": null,
  "web": "citycasarentals.com / nestsuiteliving.com",
  "url": "https://www.citycasarentals.com",
  "pub": "$1,800–2,500/月",
  "neg": "$1800/月",
  "tgt": "$1500/月",
  "cost27": "按月计",
  "mo": "$1,800",
  "monthly": 1800,
  "ls": "高（真公寓/含停车洗衣）",
  "score": 63.5,
  "tier": "B",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 45
 },
 {
  "name": "Delta Hotels by Marriott Guelph",
  "city": "Guelph",
  "type": "高端全服务",
  "bf": "?",
  "addr": "50 Stone Rd W",
  "phone": "+1 519-780-3700",
  "email": null,
  "web": "marriott.com",
  "url": "https://www.marriott.com",
  "pub": "$137–239/晚（典型 ~$190）",
  "neg": "$130/晚",
  "tgt": "$115/晚",
  "cost27": "$3,510",
  "mo": "$1,170",
  "monthly": 1170,
  "ls": "中（近UofG/超预算）",
  "score": 63.0,
  "tier": "B",
  "rating": "8.8/10",
  "rating_note": "Google·1144条 · 服务好干净近大学；隔音一般",
  "rank": 46
 },
 {
  "name": "Delta Hotels Waterloo",
  "city": "Waterloo",
  "type": "高端全服务",
  "bf": "?",
  "addr": "110 Erb St W",
  "phone": "+1 519-514-0404 (销售 514-0412)",
  "email": null,
  "web": "marriott.com",
  "url": "https://www.marriott.com",
  "pub": "$186–222/晚",
  "neg": "$175/晚",
  "tgt": "$150/晚",
  "cost27": "$4,725",
  "mo": "$1,575",
  "monthly": 1575,
  "ls": "中（销售联系/远超预算）",
  "score": 63.0,
  "tier": "B",
  "rating": "8.8/10",
  "rating_note": "Marriott·745+条 · 位置佳房间现代；停车收费、价偏高",
  "rank": 47
 },
 {
  "name": "Norfolk Guest House B&B Guelph",
  "city": "Guelph",
  "type": "民宿 B&B",
  "bf": "Y",
  "addr": "102 Eramosa Rd",
  "phone": "+1 519-767-1095",
  "email": "info@norfolkguesthouse.ca",
  "web": "norfolkguesthouse.ca",
  "url": "https://www.norfolkguesthouse.ca",
  "pub": "$129–269/晚（典型 ~$210）",
  "neg": "$140/晚",
  "tgt": "$125/晚",
  "cost27": "$3,780",
  "mo": "$1,260",
  "monthly": 1260,
  "ls": "中（短/长住皆接）",
  "score": 62.7,
  "tier": "B",
  "rating": "8.8/10",
  "rating_note": "Booking·78条 · 历史建筑美、干净含早",
  "rank": 48
 },
 {
  "name": "Blueground 家具月租公寓",
  "city": "KW",
  "type": "平台服务公寓(整租)",
  "bf": "N",
  "addr": "挂牌分布(Station Park等)",
  "phone": "平台预约",
  "email": null,
  "web": "blueground.com",
  "url": "https://www.theblueground.com/furnished-apartments/kitchener-can",
  "pub": "$2,000+/月",
  "neg": "$2200/月",
  "tgt": "$1800/月",
  "cost27": "按月计",
  "mo": "$2,200",
  "monthly": 2200,
  "ls": "高（真公寓/平台价硬）",
  "score": 58.5,
  "tier": "C",
  "rating": "—",
  "rating_note": "平台房源各异，需逐条看评论",
  "rank": 49
 },
 {
  "name": "Comfort Inn Guelph",
  "city": "Guelph",
  "type": "经济酒店",
  "bf": "?",
  "addr": "480 Silvercreek Pkwy N",
  "phone": "+1 519-763-1900",
  "email": null,
  "web": "choicehotels.com",
  "url": "https://www.choicehotels.com",
  "pub": "$210–240/晚",
  "neg": "$180/晚",
  "tgt": "$160/晚",
  "cost27": "$4,860",
  "mo": "$1,620",
  "monthly": 1620,
  "ls": "中（超预算）",
  "score": 58.2,
  "tier": "C",
  "rating": "7.8/10",
  "rating_note": "TripAdvisor·253条 · 干净性价比高；早餐简单",
  "rank": 50
 }
];
