/* locker-finder/data.js
 * 滑铁卢大学全校储物柜数据集（核验快照 2026-08-27）。
 * 数据内联为 window.LOCKERS，避免 fetch 本地文件限制（与工具箱规范一致）。
 * 字段说明：
 *   id        唯一 id（与地图 marker 对应）
 *   name_zh / name_en   中英文名称
 *   building  楼代号
 *   building_full / building_full_en  楼全称（双语）
 *   cat       分类：免费 / 租赁 / 日租（cat_en 为英文）
 *   term      租期：学期 / 日租（term_en 为英文）
 *   price     价格（中文）
 *   price_en  价格（英文）
 *   ownLock   是否需自带挂锁（ownLock_en 为英文）
 *   provider  管理方（英文专有名词，双语共用）
 *   who       适用人群 / 资格（who_en 为英文）
 *   floor     楼层（floor_en 为英文）
 *   coord     [lat, lng] 真实地理坐标（用于真实地图落点）
 *   apply_url 申请/登记网址
 *   apply_text 申请方式（apply_text_en 为英文）
 *   recommend best(首选) / good(推荐) / fallback(备选)
 *   notes_zh / notes_en  备注（资格风险等）
 */
window.LOCKERS = [
  {
    id: "science-eit",
    name_zh: "Science 免费柜 · EIT 2 楼",
    name_en: "Science Free Locker — EIT 2nd floor",
    building: "EIT",
    building_full: "Engineering Innovation Centre（ECE 主楼）",
    building_full_en: "Engineering Innovation Centre (ECE main building)",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费（一学期）",
    price_en: "Free (one term)",
    ownLock: "需自带挂锁",
    ownLock_en: "Bring your own padlock",
    provider: "Science Undergraduate Office",
    who: "全校学生（Science 管理，建议先试）",
    who_en: "All students (run by Science; try first)",
    floor: "2 楼",
    floor_en: "2nd floor",
    coord: [43.4728, -80.5442],
    apply_url: "https://uwaterloo.ca/science-undergraduate-office/new-students-science/get-science-ready/locker-registration",
    apply_text: "先到 EIT 2 楼实地占一个空柜 → 再填 Science Locker Registration 网页表单登记",
    apply_text_en: "Claim an empty locker on EIT 2F in person → then register via the Science Locker Registration web form",
    recommend: "best",
    notes_zh: "ECE 学生（工程系）也可尝试：页面由 Science 本科学办管理，未明确限制仅 Science 学生。位于 ECE 主楼、免费、自带锁，是距离最近、性价比最高的选择。若被拒，转 MathSoc / Athletics。",
    notes_en: "ECE (Engineering) students may still try — page is run by Science UG Office and does not explicitly restrict to Science students. Closest + free + bring-your-own-lock. Fallback to MathSoc/Athletics if rejected.",
  },
  {
    id: "science-stc",
    name_zh: "Science 免费柜 · STC",
    name_en: "Science Free Locker — STC",
    building: "STC",
    building_full: "Science Teaching Centre",
    building_full_en: "Science Teaching Centre",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费（一学期）",
    price_en: "Free (one term)",
    ownLock: "需自带挂锁",
    ownLock_en: "Bring your own padlock",
    provider: "Science Undergraduate Office",
    who: "全校学生（Science 管理）",
    who_en: "All students (run by Science)",
    floor: "楼层见现场",
    floor_en: "See on site",
    coord: [43.4731, -80.5432],
    apply_url: "https://uwaterloo.ca/science-undergraduate-office/new-students-science/get-science-ready/locker-registration",
    apply_text: "实地占空柜 → 填 Science Locker Registration 网页表单",
    apply_text_en: "Claim an empty locker on site → fill the Science Locker Registration web form",
    recommend: "good",
    notes_zh: "Science 楼群免费学期柜之一，与 EIT 同属 Science 登记体系。",
    notes_en: "Part of the Science faculty free-term locker network; same registration as EIT.",
  },
  {
    id: "science-c2",
    name_zh: "Science 免费柜 · C2",
    name_en: "Science Free Locker — C2",
    building: "C2",
    building_full: "Chemistry 2",
    building_full_en: "Chemistry 2",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费（一学期）",
    price_en: "Free (one term)",
    ownLock: "需自带挂锁",
    ownLock_en: "Bring your own padlock",
    provider: "Science Undergraduate Office",
    who: "全校学生（Science 管理）",
    who_en: "All students (run by Science)",
    floor: "楼层见现场",
    floor_en: "See on site",
    coord: [43.4724, -80.5421],
    apply_url: "https://uwaterloo.ca/science-undergraduate-office/new-students-science/get-science-ready/locker-registration",
    apply_text: "实地占空柜 → 填 Science Locker Registration 网页表单",
    apply_text_en: "Claim an empty locker on site → fill the Science Locker Registration web form",
    recommend: "good",
    notes_zh: "Science 楼群免费学期柜之一，偏东校区。",
    notes_en: "Part of Science free-term locker network; east campus.",
  },
  {
    id: "science-esc",
    name_zh: "Science 免费柜 · ESC",
    name_en: "Science Free Locker — ESC",
    building: "ESC",
    building_full: "Earth Sciences Centre",
    building_full_en: "Earth Sciences Centre",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费（一学期）",
    price_en: "Free (one term)",
    ownLock: "需自带挂锁",
    ownLock_en: "Bring your own padlock",
    provider: "Science Undergraduate Office",
    who: "全校学生（Science 管理）",
    who_en: "All students (run by Science)",
    floor: "楼层见现场",
    floor_en: "See on site",
    coord: [43.4717, -80.5424],
    apply_url: "https://uwaterloo.ca/science-undergraduate-office/new-students-science/get-science-ready/locker-registration",
    apply_text: "实地占空柜 → 填 Science Locker Registration 网页表单",
    apply_text_en: "Claim an empty locker on site → fill the Science Locker Registration web form",
    recommend: "good",
    notes_zh: "Science 楼群免费学期柜之一。",
    notes_en: "Part of Science free-term locker network.",
  },
  {
    id: "science-phy",
    name_zh: "Science 免费柜 · PHY",
    name_en: "Science Free Locker — PHY",
    building: "PHY",
    building_full: "Physics",
    building_full_en: "Physics",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费（一学期）",
    price_en: "Free (one term)",
    ownLock: "需自带挂锁",
    ownLock_en: "Bring your own padlock",
    provider: "Science Undergraduate Office",
    who: "全校学生（Science 管理）",
    who_en: "All students (run by Science)",
    floor: "楼层见现场",
    floor_en: "See on site",
    coord: [43.4711, -80.5432],
    apply_url: "https://uwaterloo.ca/science-undergraduate-office/new-students-science/get-science-ready/locker-registration",
    apply_text: "实地占空柜 → 填 Science Locker Registration 网页表单",
    apply_text_en: "Claim an empty locker on site → fill the Science Locker Registration web form",
    recommend: "good",
    notes_zh: "Science 楼群免费学期柜之一。",
    notes_en: "Part of Science free-term locker network.",
  },
  {
    id: "mathsoc-mc",
    name_zh: "MathSoc 租赁柜 · MC",
    name_en: "MathSoc Locker — MC",
    building: "MC",
    building_full: "Mathematics & Computer Building",
    building_full_en: "Mathematics & Computer Building",
    cat: "租赁",
    cat_en: "Rental",
    term: "学期",
    term_en: "Term",
    price: "约 $14.79 / 学期",
    price_en: "~$14.79 / term",
    ownLock: "提供组合锁（不用自带）",
    ownLock_en: "Combo lock provided (no need to bring)",
    provider: "Math Society (MathSoc)",
    who: "Math 学生为主，通常对全校开放",
    who_en: "Mainly Math students; usually open to all",
    floor: "MC 内指定区",
    floor_en: "Designated area in MC",
    coord: [43.4717, -80.5463],
    apply_url: "https://uwaterloo.ca/math/society",
    apply_text: "开学初在 MathSoc 柜台 / 网站租赁，先到先得",
    apply_text_en: "Rent at the MathSoc desk / website early in term, first-come first-served",
    recommend: "good",
    notes_zh: "全校最便宜的租赁柜之一，靠近 DC。资格：Math 学生优先，往年对全校学生开放；以当年 MathSoc 政策为准。",
    notes_en: "Among the cheapest rentals, near DC. Math students priority; historically open to all. Confirm current MathSoc policy.",
  },
  {
    id: "ath-pac",
    name_zh: "Athletics 租赁柜 · PAC",
    name_en: "Athletics Locker — PAC",
    building: "PAC",
    building_full: "Physical Activities Complex",
    building_full_en: "Physical Activities Complex",
    cat: "租赁",
    cat_en: "Rental",
    term: "学期",
    term_en: "Term",
    price: "$29.50–$40 + HST / 学期",
    price_en: "$29.50–$40 + HST / term",
    ownLock: "提供锁（具体见前台）",
    ownLock_en: "Lock provided (see front desk)",
    provider: "Athletics & Recreation",
    who: "全校学生",
    who_en: "All students",
    floor: "PAC 更衣区",
    floor_en: "PAC changeroom",
    coord: [43.4690, -80.5428],
    apply_url: "https://uwaterloo.ca/athletics",
    apply_text: "秋季学期约 9/8 开放租赁，前台或网站办理",
    apply_text_en: "Opens ~Sept 8 in fall term; at front desk or website",
    recommend: "fallback",
    notes_zh: "对全校学生开放，但离 ECE 楼较远；适合常去健身房的人。秋季开学初开放，名额有限。",
    notes_en: "Open to all students but far from ECE; good if you use the gym. Fall term opens ~Sept 8, limited spots.",
  },
  {
    id: "ath-cif",
    name_zh: "Athletics 租赁柜 · CIF",
    name_en: "Athletics Locker — CIF",
    building: "CIF",
    building_full: "Columbia Icefield",
    building_full_en: "Columbia Icefield",
    cat: "租赁",
    cat_en: "Rental",
    term: "学期",
    term_en: "Term",
    price: "$29.50–$40 + HST / 学期",
    price_en: "$29.50–$40 + HST / term",
    ownLock: "提供锁（具体见前台）",
    ownLock_en: "Lock provided (see front desk)",
    provider: "Athletics & Recreation",
    who: "全校学生",
    who_en: "All students",
    floor: "CIF 更衣区",
    floor_en: "CIF changeroom",
    coord: [43.4680, -80.5433],
    apply_url: "https://uwaterloo.ca/athletics",
    apply_text: "秋季学期约 9/8 开放租赁，前台或网站办理",
    apply_text_en: "Opens ~Sept 8 in fall term; at front desk or website",
    recommend: "fallback",
    notes_zh: "与 PAC 同属 Athletics 体系，靠近运动场。",
    notes_en: "Same Athletics system as PAC, by the fields.",
  },
  {
    id: "ess-ev",
    name_zh: "ESS 免费柜 · Environment",
    name_en: "ESS Locker — Environment",
    building: "EV",
    building_full: "Environment Village (EV1/EV2/ENV)",
    building_full_en: "Environment Village (EV1/EV2/ENV)",
    cat: "免费",
    cat_en: "Free",
    term: "学期",
    term_en: "Term",
    price: "免费 / 低价（Environment 学生）",
    price_en: "Free / low-cost (Environment students)",
    ownLock: "见 ESS 规定",
    ownLock_en: "Per ESS rules",
    provider: "Environment Society (ESS)",
    who: "仅 Environment 学院学生",
    who_en: "Environment faculty students only",
    floor: "EV 楼内",
    floor_en: "Inside EV",
    coord: [43.4692, -80.5478],
    apply_url: "https://uwaterloo.ca/environment",
    apply_text: "通过 Environment Society 申请，限 Environment 学生",
    apply_text_en: "Apply via Environment Society; Environment students only",
    recommend: "fallback",
    notes_zh: "仅限 Environment 学院学生，ECE 学生通常不符合资格——列为备选仅供参考。",
    notes_en: "Environment students only; ECE students normally not eligible. Listed as fallback reference only.",
  },
  {
    id: "lib-dana",
    name_zh: "图书馆日租柜 · Dana Porter",
    name_en: "Library Day-use Locker — Dana Porter",
    building: "LIB",
    building_full: "Dana Porter Library（含 DC 日租柜）",
    building_full_en: "Dana Porter Library (incl. DC day-use lockers)",
    cat: "日租",
    cat_en: "Day-use",
    term: "日租",
    term_en: "Day-use",
    price: "免费（当日 8 小时）",
    price_en: "Free (8-hour day-use)",
    ownLock: "不用自带（现场取号/系统）",
    ownLock_en: "Not needed (on-site number / system)",
    provider: "University of Waterloo Libraries",
    who: "全校学生 / 教职工",
    who_en: "All students / staff",
    floor: "Dana Porter 6 楼（DC 也有）",
    floor_en: "Dana Porter 6F (also at DC)",
    coord: [43.4719, -80.5453],
    apply_url: "https://uwaterloo.ca/libraries",
    apply_text: "现场自助取号，当天归还，不适合长期存放",
    apply_text_en: "Self-serve number on site, return same day; not for long-term storage",
    recommend: "good",
    notes_zh: "免费、当日有效（约 8 小时），适合白天临时放书；不可过夜长期存。Dana Porter 与 Davis Centre 均有。",
    notes_en: "Free, same-day (~8h) only — good for daytime books, not overnight storage. Available at Dana Porter and Davis Centre.",
  },
  {
    id: "qnc-day",
    name_zh: "QNC 日租柜 · Quantum Nano",
    name_en: "QNC Day-use Locker — Quantum Nano Centre",
    building: "QNC",
    building_full: "Mike & Ophelia Lazaridis Quantum-Nano Centre",
    building_full_en: "Mike & Ophelia Lazaridis Quantum-Nano Centre",
    cat: "日租",
    cat_en: "Day-use",
    term: "日租",
    term_en: "Day-use",
    price: "免费 / 低价（当日）",
    price_en: "Free / low-cost (day-use)",
    ownLock: "见现场规定",
    ownLock_en: "Per on-site rules",
    provider: "Quantum Nano Centre",
    who: "全校学生（以 QNC 规定为准）",
    who_en: "All students (per QNC rules)",
    floor: "QNC 内",
    floor_en: "Inside QNC",
    coord: [43.4722, -80.5446],
    apply_url: "https://uwaterloo.ca/quantum-nano-centre",
    apply_text: "现场办理日租，具体以 QNC 前台为准",
    apply_text_en: "Day-use on site; per QNC front desk",
    recommend: "good",
    notes_zh: "校园中心位置，日租为主；适合白天在 QNC / 中校区活动时使用。",
    notes_en: "Central location; day-use oriented. Good for daytime use around the mid-campus.",
  }
];
